apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: composer
  name: composer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: composer
    spec:
      containers:
      - image: composer:latest
        name: composer
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: composer-claim0
        workingDir: /var/www/html
      restartPolicy: Always
      volumes:
      - name: composer-claim0
        persistentVolumeClaim:
          claimName: composer-claim0
status: {}
