apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
        - name: SERVICE_NAME
          value: mysql
        - name: SERVICE_TAGS
          value: dev
        image: mysql:5.7.30
        name: mysql
        ports:
        - containerPort: 4306
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: sql-volume
      restartPolicy: Always
      volumes:
      - name: sql-volume
        persistentVolumeClaim:
          claimName: sql-volume
status: {}
