apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: npm
  name: npm
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: npm
    spec:
      containers:
      - command:
        - npm
        image: node:14.5
        name: npm
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: npm-claim0
        workingDir: /var/www/html
      restartPolicy: Always
      volumes:
      - name: npm-claim0
        persistentVolumeClaim:
          claimName: npm-claim0
status: {}
